/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Box {
  
  @SerializedName("left")
  private Float left = null;
  @SerializedName("right")
  private Float right = null;
  @SerializedName("top")
  private Float top = null;
  @SerializedName("bottom")
  private Float bottom = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getLeft() {
    return left;
  }
  public void setLeft(Float left) {
    this.left = left;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getRight() {
    return right;
  }
  public void setRight(Float right) {
    this.right = right;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getTop() {
    return top;
  }
  public void setTop(Float top) {
    this.top = top;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getBottom() {
    return bottom;
  }
  public void setBottom(Float bottom) {
    this.bottom = bottom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Box box = (Box) o;
    return (this.left == null ? box.left == null : this.left.equals(box.left)) &&
        (this.right == null ? box.right == null : this.right.equals(box.right)) &&
        (this.top == null ? box.top == null : this.top.equals(box.top)) &&
        (this.bottom == null ? box.bottom == null : this.bottom.equals(box.bottom));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.left == null ? 0: this.left.hashCode());
    result = 31 * result + (this.right == null ? 0: this.right.hashCode());
    result = 31 * result + (this.top == null ? 0: this.top.hashCode());
    result = 31 * result + (this.bottom == null ? 0: this.bottom.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Box {\n");
    
    sb.append("  left: ").append(left).append("\n");
    sb.append("  right: ").append(right).append("\n");
    sb.append("  top: ").append(top).append("\n");
    sb.append("  bottom: ").append(bottom).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
