/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.BoxArray;
import io.swagger.client.model.Product;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BoxObject {
  
  @SerializedName("box")
  private BoxArray box = null;
  @SerializedName("class_code")
  private String classCode = null;
  @SerializedName("class_name")
  private String className = null;
  @SerializedName("products")
  private List<Product> products = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BoxArray getBox() {
    return box;
  }
  public void setBox(BoxArray box) {
    this.box = box;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getClassCode() {
    return classCode;
  }
  public void setClassCode(String classCode) {
    this.classCode = classCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getClassName() {
    return className;
  }
  public void setClassName(String className) {
    this.className = className;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Product> getProducts() {
    return products;
  }
  public void setProducts(List<Product> products) {
    this.products = products;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoxObject boxObject = (BoxObject) o;
    return (this.box == null ? boxObject.box == null : this.box.equals(boxObject.box)) &&
        (this.classCode == null ? boxObject.classCode == null : this.classCode.equals(boxObject.classCode)) &&
        (this.className == null ? boxObject.className == null : this.className.equals(boxObject.className)) &&
        (this.products == null ? boxObject.products == null : this.products.equals(boxObject.products));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.box == null ? 0: this.box.hashCode());
    result = 31 * result + (this.classCode == null ? 0: this.classCode.hashCode());
    result = 31 * result + (this.className == null ? 0: this.className.hashCode());
    result = 31 * result + (this.products == null ? 0: this.products.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoxObject {\n");
    
    sb.append("  box: ").append(box).append("\n");
    sb.append("  classCode: ").append(classCode).append("\n");
    sb.append("  className: ").append(className).append("\n");
    sb.append("  products: ").append(products).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
