/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.BoxObject;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetObjectsByProductIdResponseData {
  
  @SerializedName("boxes")
  private List<BoxObject> boxes = null;
  @SerializedName("product_id")
  private String productId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public List<BoxObject> getBoxes() {
    return boxes;
  }
  public void setBoxes(List<BoxObject> boxes) {
    this.boxes = boxes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductId() {
    return productId;
  }
  public void setProductId(String productId) {
    this.productId = productId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetObjectsByProductIdResponseData getObjectsByProductIdResponseData = (GetObjectsByProductIdResponseData) o;
    return (this.boxes == null ? getObjectsByProductIdResponseData.boxes == null : this.boxes.equals(getObjectsByProductIdResponseData.boxes)) &&
        (this.productId == null ? getObjectsByProductIdResponseData.productId == null : this.productId.equals(getObjectsByProductIdResponseData.productId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.boxes == null ? 0: this.boxes.hashCode());
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetObjectsByProductIdResponseData {\n");
    
    sb.append("  boxes: ").append(boxes).append("\n");
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
