/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.BoxesArray;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetObjectsResponseData {
  
  @SerializedName("boxes")
  private BoxesArray boxes = null;
  @SerializedName("image_id")
  private String imageId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BoxesArray getBoxes() {
    return boxes;
  }
  public void setBoxes(BoxesArray boxes) {
    this.boxes = boxes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getImageId() {
    return imageId;
  }
  public void setImageId(String imageId) {
    this.imageId = imageId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetObjectsResponseData getObjectsResponseData = (GetObjectsResponseData) o;
    return (this.boxes == null ? getObjectsResponseData.boxes == null : this.boxes.equals(getObjectsResponseData.boxes)) &&
        (this.imageId == null ? getObjectsResponseData.imageId == null : this.imageId.equals(getObjectsResponseData.imageId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.boxes == null ? 0: this.boxes.hashCode());
    result = 31 * result + (this.imageId == null ? 0: this.imageId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetObjectsResponseData {\n");
    
    sb.append("  boxes: ").append(boxes).append("\n");
    sb.append("  imageId: ").append(imageId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
