/**
 * style-api
 * This is a API document for Stylens Service
 *
 * OpenAPI spec version: 0.0.1
 * Contact: master@bluehack.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Product {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("host_code")
  private String hostCode = null;
  @SerializedName("host_url")
  private String hostUrl = null;
  @SerializedName("host_name")
  private String hostName = null;
  @SerializedName("tags")
  private List<String> tags = null;
  @SerializedName("class_code")
  private String classCode = null;
  @SerializedName("price")
  private Integer price = null;
  @SerializedName("currency_unit")
  private String currencyUnit = null;
  @SerializedName("product_url")
  private String productUrl = null;
  @SerializedName("product_no")
  private String productNo = null;
  @SerializedName("nation")
  private String nation = null;
  @SerializedName("main_image")
  private String mainImage = null;
  @SerializedName("main_image_mobile_full")
  private String mainImageMobileFull = null;
  @SerializedName("main_image_mobile_thumb")
  private String mainImageMobileThumb = null;
  @SerializedName("sizes")
  private List<String> sizes = null;
  @SerializedName("discount_rate")
  private Integer discountRate = null;
  @SerializedName("version")
  private String version = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHostCode() {
    return hostCode;
  }
  public void setHostCode(String hostCode) {
    this.hostCode = hostCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHostUrl() {
    return hostUrl;
  }
  public void setHostUrl(String hostUrl) {
    this.hostUrl = hostUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHostName() {
    return hostName;
  }
  public void setHostName(String hostName) {
    this.hostName = hostName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getClassCode() {
    return classCode;
  }
  public void setClassCode(String classCode) {
    this.classCode = classCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getPrice() {
    return price;
  }
  public void setPrice(Integer price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyUnit() {
    return currencyUnit;
  }
  public void setCurrencyUnit(String currencyUnit) {
    this.currencyUnit = currencyUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductUrl() {
    return productUrl;
  }
  public void setProductUrl(String productUrl) {
    this.productUrl = productUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getProductNo() {
    return productNo;
  }
  public void setProductNo(String productNo) {
    this.productNo = productNo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNation() {
    return nation;
  }
  public void setNation(String nation) {
    this.nation = nation;
  }

  /**
   * image url
   **/
  @ApiModelProperty(value = "image url")
  public String getMainImage() {
    return mainImage;
  }
  public void setMainImage(String mainImage) {
    this.mainImage = mainImage;
  }

  /**
   * Mobile full size of image url
   **/
  @ApiModelProperty(value = "Mobile full size of image url")
  public String getMainImageMobileFull() {
    return mainImageMobileFull;
  }
  public void setMainImageMobileFull(String mainImageMobileFull) {
    this.mainImageMobileFull = mainImageMobileFull;
  }

  /**
   * Mobile thumbnail size of image url
   **/
  @ApiModelProperty(value = "Mobile thumbnail size of image url")
  public String getMainImageMobileThumb() {
    return mainImageMobileThumb;
  }
  public void setMainImageMobileThumb(String mainImageMobileThumb) {
    this.mainImageMobileThumb = mainImageMobileThumb;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getSizes() {
    return sizes;
  }
  public void setSizes(List<String> sizes) {
    this.sizes = sizes;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDiscountRate() {
    return discountRate;
  }
  public void setDiscountRate(Integer discountRate) {
    this.discountRate = discountRate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }
  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return (this.id == null ? product.id == null : this.id.equals(product.id)) &&
        (this.name == null ? product.name == null : this.name.equals(product.name)) &&
        (this.hostCode == null ? product.hostCode == null : this.hostCode.equals(product.hostCode)) &&
        (this.hostUrl == null ? product.hostUrl == null : this.hostUrl.equals(product.hostUrl)) &&
        (this.hostName == null ? product.hostName == null : this.hostName.equals(product.hostName)) &&
        (this.tags == null ? product.tags == null : this.tags.equals(product.tags)) &&
        (this.classCode == null ? product.classCode == null : this.classCode.equals(product.classCode)) &&
        (this.price == null ? product.price == null : this.price.equals(product.price)) &&
        (this.currencyUnit == null ? product.currencyUnit == null : this.currencyUnit.equals(product.currencyUnit)) &&
        (this.productUrl == null ? product.productUrl == null : this.productUrl.equals(product.productUrl)) &&
        (this.productNo == null ? product.productNo == null : this.productNo.equals(product.productNo)) &&
        (this.nation == null ? product.nation == null : this.nation.equals(product.nation)) &&
        (this.mainImage == null ? product.mainImage == null : this.mainImage.equals(product.mainImage)) &&
        (this.mainImageMobileFull == null ? product.mainImageMobileFull == null : this.mainImageMobileFull.equals(product.mainImageMobileFull)) &&
        (this.mainImageMobileThumb == null ? product.mainImageMobileThumb == null : this.mainImageMobileThumb.equals(product.mainImageMobileThumb)) &&
        (this.sizes == null ? product.sizes == null : this.sizes.equals(product.sizes)) &&
        (this.discountRate == null ? product.discountRate == null : this.discountRate.equals(product.discountRate)) &&
        (this.version == null ? product.version == null : this.version.equals(product.version));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.hostCode == null ? 0: this.hostCode.hashCode());
    result = 31 * result + (this.hostUrl == null ? 0: this.hostUrl.hashCode());
    result = 31 * result + (this.hostName == null ? 0: this.hostName.hashCode());
    result = 31 * result + (this.tags == null ? 0: this.tags.hashCode());
    result = 31 * result + (this.classCode == null ? 0: this.classCode.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.currencyUnit == null ? 0: this.currencyUnit.hashCode());
    result = 31 * result + (this.productUrl == null ? 0: this.productUrl.hashCode());
    result = 31 * result + (this.productNo == null ? 0: this.productNo.hashCode());
    result = 31 * result + (this.nation == null ? 0: this.nation.hashCode());
    result = 31 * result + (this.mainImage == null ? 0: this.mainImage.hashCode());
    result = 31 * result + (this.mainImageMobileFull == null ? 0: this.mainImageMobileFull.hashCode());
    result = 31 * result + (this.mainImageMobileThumb == null ? 0: this.mainImageMobileThumb.hashCode());
    result = 31 * result + (this.sizes == null ? 0: this.sizes.hashCode());
    result = 31 * result + (this.discountRate == null ? 0: this.discountRate.hashCode());
    result = 31 * result + (this.version == null ? 0: this.version.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  hostCode: ").append(hostCode).append("\n");
    sb.append("  hostUrl: ").append(hostUrl).append("\n");
    sb.append("  hostName: ").append(hostName).append("\n");
    sb.append("  tags: ").append(tags).append("\n");
    sb.append("  classCode: ").append(classCode).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  currencyUnit: ").append(currencyUnit).append("\n");
    sb.append("  productUrl: ").append(productUrl).append("\n");
    sb.append("  productNo: ").append(productNo).append("\n");
    sb.append("  nation: ").append(nation).append("\n");
    sb.append("  mainImage: ").append(mainImage).append("\n");
    sb.append("  mainImageMobileFull: ").append(mainImageMobileFull).append("\n");
    sb.append("  mainImageMobileThumb: ").append(mainImageMobileThumb).append("\n");
    sb.append("  sizes: ").append(sizes).append("\n");
    sb.append("  discountRate: ").append(discountRate).append("\n");
    sb.append("  version: ").append(version).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
